# Generated by Django 5.1.6 on 2025-12-22 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partnerlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Дата мягкого удаления записи. NULL если запись активна.', null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked'), ('Удалено', 'Deleted')], default='На модерации', verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['deleted_at'], name='partners_pl_deleted_00242b_idx'),
        ),
    ]
