# Generated by Django 5.1.6 on 2025-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0007_projectparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Дата мягкого удаления записи. NULL если запись активна.', null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked'), ('Удалено', 'Deleted')], default='На модерации', verbose_name='Статус'),
        ),
    ]
