# Generated by Django 5.1.6 on 2026-01-06 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0008_project_deleted_at_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='action_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Название целевого действия'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(default='', help_text='Ссылка проекта', max_length=150, verbose_name='URL проекта'),
        ),
    ]
