# Generated by Django 5.1.6 on 2025-12-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('project', 'Проект'), ('platform', 'Платформа'), ('new_user', 'Новый пользователь'), ('payout', 'Выплата'), ('system', 'Системное уведомление'), ('other', 'Другое')], max_length=20, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Детали')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='managers.managerprofile', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Активность менеджра',
                'verbose_name_plural': 'Активности менеджеров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manager', 'is_read'], name='managers_ma_manager_bb1ee3_idx')],
            },
        ),
    ]
