# Generated by Django 5.1.6 on 2025-12-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manageractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageractivity',
            name='activity_type',
            field=models.CharField(choices=[('project', 'Проект'), ('platform', 'Платформа'), ('new_user', 'Новый пользователь'), ('payout', 'Выплата'), ('top_up', 'Пополнение баланса'), ('review', 'Отзыв'), ('system', 'Системное уведомление'), ('other', 'Другое')], max_length=20, verbose_name='Тип активности'),
        ),
    ]
