# Generated by Django 5.1.6 on 2025-12-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='referrer',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Источник'),
        ),
    ]
